name: patternscoring
favicon: null
layout_spectrum: 0.47169220726937056
typography_spectrum: 0.06192445429041982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.59871058142744
  lightness: 0.22877114568836987
  saturation: 0.2941387393511832
  rhythmicContrast: 0.6723643497098237
purpose: []
